//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Words.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Words.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все найденные слова:.
        /// </summary>
        internal static string allWords {
            get {
                return ResourceManager.GetString("allWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите изначальное слово:.
        /// </summary>
        internal static string enterWordPrompt {
            get {
                return ResourceManager.GetString("enterWordPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите имя первого игрока:.
        /// </summary>
        internal static string firstPlayerNamePrompt {
            get {
                return ResourceManager.GetString("firstPlayerNamePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слово содержит неверные символы. Введите повторно..
        /// </summary>
        internal static string invalidCharactersError {
            get {
                return ResourceManager.GetString("invalidCharactersError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный выбор. Повторите выбор..
        /// </summary>
        internal static string invalidChoiceMessage {
            get {
                return ResourceManager.GetString("invalidChoiceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный игрок..
        /// </summary>
        internal static string invalidPlayerError {
            get {
                return ResourceManager.GetString("invalidPlayerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добро пожаловать в меню выбора языка:
        ///  1. Русский.
        ///  2. Английский.
        ///  3. Продолжить с текущим..
        /// </summary>
        internal static string languageMenuHead {
            get {
                return ResourceManager.GetString("languageMenuHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слово содержит буквы не из исходного. Введите повторно..
        /// </summary>
        internal static string lettersFromOriginalError {
            get {
                return ResourceManager.GetString("lettersFromOriginalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Меню: 
        ///  1. Выбор языка игры.
        ///  2. Выбор режима игры.
        ///  3. Начать игру..
        /// </summary>
        internal static string menuHead {
            get {
                return ResourceManager.GetString("menuHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ход игрока {0}.
        /// </summary>
        internal static string playerTurn {
            get {
                return ResourceManager.GetString("playerTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слова игрока {0}.
        /// </summary>
        internal static string playerWordsHeader {
            get {
                return ResourceManager.GetString("playerWordsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество оставшихся попыток: {0}.
        /// </summary>
        internal static string remainingAttemptsMessage {
            get {
                return ResourceManager.GetString("remainingAttemptsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слово подходит!.
        /// </summary>
        internal static string rightWord {
            get {
                return ResourceManager.GetString("rightWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Победитель {0}.
        /// </summary>
        internal static string roundWinnerMessage {
            get {
                return ResourceManager.GetString("roundWinnerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите имя второго игрока:.
        /// </summary>
        internal static string secondPlayerNamePrompt {
            get {
                return ResourceManager.GetString("secondPlayerNamePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добро пожаловать в меню выбора таймера:
        ///  1. 2 минуты.
        ///  2. 1 минута.
        ///  3. 30 секунд.
        ///  4. 10 секунд.
        ///  5. Продолжить без таймера..
        /// </summary>
        internal static string timerMenuHead {
            get {
                return ResourceManager.GetString("timerMenuHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время вышло! Ход игрока завершен..
        /// </summary>
        internal static string timeUpMessage {
            get {
                return ResourceManager.GetString("timeUpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество слов: {0}.
        /// </summary>
        internal static string wordCountMessage {
            get {
                return ResourceManager.GetString("wordCountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слово имеет неверную длинну. Введите повторно..
        /// </summary>
        internal static string wordLengthError {
            get {
                return ResourceManager.GetString("wordLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слово уже было использовано одним из игроков. Введите повторно..
        /// </summary>
        internal static string wordUsedError {
            get {
                return ResourceManager.GetString("wordUsedError", resourceCulture);
            }
        }
    }
}
